//creating quiz
export const CREATE_QUIZ_REQUEST = "CREATE_QUIZ_REQUEST";
export const CREATE_QUIZ_SUCCESS = "CREATE_QUIZ_SUCCESS";
export const CREATE_QUIZ_FAILURE = "CREATE_QUIZ_FAILURE";



export  const FETCH_QUIZ_REQUEST="FETCH_QUIZ_REQUEST";
export  const FETCH_QUIZ_SUCCESS="FETCH_QUIZ_SUCCESS";
export  const FETCH_QUIZ_FAILURE="FETCH_QUIZ_FAILURE";

export const GET_CURRENT_QUIZ_REQUEST="GET_CURRENT_QUIZ_REQUEST";
export const GET_CURRENT_QUIZ_SUCCESS="GET_CURRENT_QUIZ_SUCCESS";
export const GET_CURRENT_QUIZ_FAILURE="GET_CURRENT_QUIZ_FAILURE";


export const GETCOUNTDATA="GETCOUNTDATA";

export const GETUSERID="GETUSERID";

export const GETUSERNAME="GETUSERNAME";

export const LOGOUTUSER="LOGOUTUSER";