//creating quiz
export const CREATE_QUIZ_REQUEST = "CREATE_QUIZ_REQUEST";
export const CREATE_QUIZ_SUCCESS = "CREATE_QUIZ_SUCCESS";
export const CREATE_QUIZ_FAILURE = "CREATE_QUIZ_FAILURE";

export const FETCH_QUIZ_REQUEST = "FETCH_QUIZ_REQUEST";
export const FETCH_QUIZ_SUCCESS = "FETCH_QUIZ_SUCCESS";
export const FETCH_QUIZ_FAILURE = "FETCH_QUIZ_FAILURE";

export const GET_CURRENT_QUIZ_REQUEST = "GET_CURRENT_QUIZ_REQUEST";
export const GET_CURRENT_QUIZ_SUCCESS = "GET_CURRENT_QUIZ_SUCCESS";
export const GET_CURRENT_QUIZ_FAILURE = "GET_CURRENT_QUIZ_FAILURE";

export const GETCOUNTDATA = "GETCOUNTDATA";

export const GETUSERID = "GETUSERID";

export const GETUSERNAME = "GETUSERNAME";

export const LOGOUTUSER = "LOGOUTUSER";

export const GETADMINID = "GETADMINID";

export const GETADMINNAME = "GETADMINNAME";

export const GET_ALL_USER_DATA_REQUEST = "GET_ALL_USER_DATA_REQUEST";
export const GET_ALL_USER_DATA_SUCCESS = "GET_ALL_USER_DATA_SUCCESS";
export const GET_ALL_USER_DATA_FAILURE = "GET_ALL_USER_DATA_FAILURE";

// ----------- answer array to the user backend------------------------
export const POST_USER_RESULT_SUCCESS = "POST_USER_RESULT_SUCCESS";
export const POST_USER_RESULT_REQUEST = "POST_USER_RESULT_REQUEST";
export const POST_USER_RESULT_FAILURE = "POST_USER_RESULT_FAILURE";

//post result to redux
export const SET_USER_RESULT_SUCCESS = "SET_USER_RESULT_SUCCESS";
